### PR TITLE
expect included module ActiveTriples::RDFSource instead of single inheritence from ActiveTriples::Resource, per ActiveTriples 0.7.0

### PR DESCRIPTION
**Pull request by ndushay**
@elrayle   it would be awesome if you merged this and cut a new release of active_triples-local_name ASAP.

This was the motivation for my changes:  https://github.com/ActiveTriples/ActiveTriples/blob/develop/CHANGES.md

I'm trying to create a PR for open_annotation_rdf for more recent active-triples and rdf gems, and this dependency is a part of that.

Note that we've tried to avoid having pinned gem versions;  if you prefer pinned, I think ~> 0.7.0 or ~> 0.8.1 will both work fine.  :smile:

### CODE REVIEW

**Comment by elrayle** [comment]
Hi Naomi,

I have some changes pending to update all the gems to ActiveTriples 0.7.  ActiveTriples 0.8 is not ready for use with open annotation due to issue https://github.com/ActiveTriples/ActiveTriples/issues/147.

I can look at pushing the changes tomorrow.

Lynette

**Comment by ndushay** [comment]
@elrayle it would be great to get updated gems.  I'm really only interested in ld4l/open_annotation_rdf but ended up here by following the dependency chains.  :-)

**Comment by ndushay** [comment]
Hi Lynette - any progress with these?

**Comment by elrayle** [comment]
Looking into issues with upgrades from ActiveTriples 0.6 - 0.7 - 0.8.  See https://github.com/ActiveTriples/ActiveTriples/issues/154

**Comment by elrayle** [comment]
Replaced with PR https://github.com/ActiveTriples/active_triples-local_name/pull/3 which is compatible with all current versions of ActiveTriples.

**Pull request closed without merging**
